### ISSUE TITLE
Commands TODO

### ISSUE THREAD

**Issue by karelmikie3** [HxCKDMS/HxCCore#28]
- [x] AFK
- [x] Back
- [x] Draw
- [x] Exterminate
- [x] Help
- [x] Kit
- [x] MakeItRain(previously unimplemented)
- [x] Mute
- [x] Override
- [x] Path
- [x] Powertool(requires fake player)
- [x] Protect
- [x] Sudo
- [ ] Ghost (no collision)
- [ ] FillInventory (fills players inventory or nearby inventory with # of item (no limit))
- [ ] GroupSummon (summon multiple entities)
- [ ] PingAverage (Gives average ping after # seconds)
- [ ] Portal (binds block to warp or x y z)
